set(SUPPORTS_CXX "FALSE")
if("${COMPILER}" STREQUAL "intel")
  set(SUPPORTS_CXX "TRUE")
  set(CFLAGS "-O2 -fp-model precise -std=gnu99")
  set(CXX_LINKER "FORTRAN")
  set(FC_AUTO_R8 "-r8")
  set(FFLAGS "-convert big_endian -assume byterecl -ftz -traceback -assume realloc_lhs -fp-model source")
  set(FFLAGS_NOOPT "-O0")
  set(FIXEDFLAGS "-fixed -132")
  set(FREEFLAGS "-free")
  set(HAS_F2008_CONTIGUOUS "TRUE")
  set(MPICC "mpicc")
  set(MPICXX "mpicxx")
  set(MPIFC "mpif90")
  set(SCC "icc")
  set(SCXX "icpc")
  set(SFC "ifort")
  set(CXXFLAGS "-std=c++11 -fp-model source")
  set(CXX_LDFLAGS "-cxxlib")
endif()
if("${COMPILER}" STREQUAL "gnu")
  set(CFLAGS "-mcmodel=medium")
  set(FFLAGS_NOOPT "-O0")
  set(HAS_F2008_CONTIGUOUS "FALSE")
endif()
if("${COMPILER}" STREQUAL "gnu")
  set(SUPPORTS_CXX "TRUE")
  set(CXX_LINKER "FORTRAN")
  set(FC_AUTO_R8 "-fdefault-real-8")
  set(FFLAGS "-O -fconvert=big-endian -ffree-line-length-none -ffixed-line-length-none -fno-range-check")
  set(FIXEDFLAGS "-ffixed-form")
  set(FREEFLAGS "-ffree-form")
  set(MPICC "mpicc")
  set(MPICXX "mpic++")
  set(MPIFC "mpif90")
  set(SCC "gcc")
  set(SCXX "g++")
  set(SFC "gfortran")
  set(HDF5_PATH "/software/dev_tools/swtree/cs400_centos7.2_pe2016-08/hdf5-parallel/1.10.6/centos7.5_gnu8.1.0")
  set(NETCDF_PATH "/software/dev_tools/swtree/cs400_centos7.2_pe2016-08/netcdf-hdf5parallel/4.3.3.1/centos7.2_gnu5.3.0")
  set(NETCDF_C_PATH "/software/dev_tools/swtree/cs400_centos7.2_pe2016-08/netcdf/4.3.3.1/centos7.2_gnu5.3.0")
  set(NETCDF_FORTRAN_PATH "/software/dev_tools/swtree/cs400_centos7.2_pe2016-08/netcdf/4.3.3.1/centos7.2_gnu5.3.0")
  set(PNETCDF_PATH "/software/dev_tools/swtree/cs400_centos7.2_pe2016-08/pnetcdf/1.9.0/centos7.2_gnu5.3.0")
  set(LAPACK_LIBDIR "/software/tools/compilers/intel_2017/mkl/lib/intel64")
endif()
if("${MODEL}" STREQUAL "ice")
  set(CPPDEFS "${CPPDEFS}  -DUSE_PIO2 -DCPL_BYPASS")
endif()
if("${MODEL}" STREQUAL "ocn")
  set(CPPDEFS "${CPPDEFS}  -DUSE_PIO2 -DCPL_BYPASS")
endif()
if("${MODEL}" STREQUAL "glc")
  set(CPPDEFS "${CPPDEFS}  -DUSE_PIO2 -DCPL_BYPASS")
endif()
if("${COMPILER}" STREQUAL "gnu")
  set(CPPDEFS "${CPPDEFS}  -DFORTRANUNDERSCORE -DNO_R16 -DCPRGNU -DCPL_BYPASS")
  set(CPPDEFS "${CPPDEFS}  -DFORTRANUNDERSCORE -DNO_R16 -DCPL_BYPASS")
  if("${compile_threaded}" STREQUAL "TRUE")
    set(CFLAGS "${CFLAGS}  -fopenmp")
    set(CFLAGS "${CFLAGS}  -fopenmp")
  endif()
  if("${MODEL}" STREQUAL "csm_share")
    set(CFLAGS "${CFLAGS}  -std=c99")
  endif()
  if("${compile_threaded}" STREQUAL "TRUE")
    set(FFLAGS "${FFLAGS}  -fopenmp")
    set(FFLAGS "${FFLAGS}  -fopenmp")
  endif()
  if("${DEBUG}" STREQUAL "TRUE")
    set(CFLAGS "${CFLAGS}  -g -Wall -Og -fbacktrace -fcheck=bounds -ffpe-trap=invalid,zero,overflow")
    set(FFLAGS "${FFLAGS}  -g -Wall -Og -fbacktrace -fcheck=bounds -ffpe-trap=invalid,zero,overflow")
    set(FFLAGS "${FFLAGS}  -g -Wall")
  endif()
  if("${DEBUG}" STREQUAL "FALSE")
    set(CFLAGS "${CFLAGS}  -O")
    set(FFLAGS "${FFLAGS}  -O")
  endif()
  if("${MODEL}" STREQUAL "cism")
    set(CMAKE_OPTS "${CMAKE_OPTS}  -D CISM_GNU=ON")
    set(CMAKE_OPTS "${CMAKE_OPTS}  -D CISM_GNU=ON")
  endif()
endif()
if("${COMPILER}" STREQUAL "intel")
  set(CPPDEFS "${CPPDEFS}  -DFORTRANUNDERSCORE -DNO_R16 -DCPRINTEL -DCPL_BYPASS")
  if("${compile_threaded}" STREQUAL "TRUE")
    set(CFLAGS "${CFLAGS}  -qopenmp")
    set(FFLAGS "${FFLAGS}  -qopenmp")
    set(CXXFLAGS "${CXXFLAGS}  -qopenmp")
  endif()
  if("${DEBUG}" STREQUAL "FALSE")
    set(CFLAGS "${CFLAGS}  -O2 -debug minimal")
    set(FFLAGS "${FFLAGS}  -O2 -debug minimal")
    set(CXXFLAGS "${CXXFLAGS}  -O2")
  endif()
  if("${DEBUG}" STREQUAL "TRUE")
    set(CFLAGS "${CFLAGS}  -O0 -g")
    set(FFLAGS "${FFLAGS}  -O0 -g -check uninit -check bounds -check pointers -fpe0 -check noarg_temp_created")
    set(CXXFLAGS "${CXXFLAGS}  -O0 -g")
  endif()
endif()
if("${COMPILER}" STREQUAL "gnu")
  if("${compile_threaded}" STREQUAL "TRUE")
    set(LDFLAGS "${LDFLAGS}  -fopenmp")
    set(LDFLAGS "${LDFLAGS}  -fopenmp")
  endif()
  if("${MODEL}" STREQUAL "driver")
    set(LDFLAGS "${LDFLAGS}  -L${NETCDF_PATH}/lib -Wl,-rpath=${NETCDF_PATH}/lib -lnetcdff -lnetcdf")
  endif()
endif()
if("${COMPILER}" STREQUAL "intel")
  if("${compile_threaded}" STREQUAL "TRUE")
    set(LDFLAGS "${LDFLAGS}  -qopenmp")
  endif()
endif()
