set(SUPPORTS_CXX "FALSE")
if("${COMPILER}" STREQUAL "intel")
  set(MPIFC "mpif90")
  set(FFLAGS_NOOPT "-O0")
  set(CXXFLAGS "-std=c++11 -fp-model source")
  set(MPICC "mpicc")
  set(SCC "icc")
  set(MPICXX "mpicxx")
  set(HAS_F2008_CONTIGUOUS "TRUE")
  set(CXX_LDFLAGS "-cxxlib")
  set(SUPPORTS_CXX "TRUE")
  set(FFLAGS "-convert big_endian -assume byterecl -ftz -traceback -assume realloc_lhs -fp-model source")
  set(FIXEDFLAGS "-fixed -132")
  set(CXX_LINKER "FORTRAN")
  set(FC_AUTO_R8 "-r8")
  set(CFLAGS "-O2 -fp-model precise -std=gnu99")
  set(FREEFLAGS "-free")
  set(SFC "ifort")
  set(SCXX "icpc")
endif()
if("${COMPILER}" STREQUAL "gnu")
  set(MPIFC "mpif90")
  set(FFLAGS_NOOPT "-O0")
  set(MPICC "mpicc")
  set(SCC "gcc")
  set(MPICXX "mpicxx")
  set(HAS_F2008_CONTIGUOUS "FALSE")
  set(SUPPORTS_CXX "TRUE")
  set(FFLAGS "-mcmodel=medium -fconvert=big-endian -ffree-line-length-none -ffixed-line-length-none")
  set(FIXEDFLAGS "-ffixed-form")
  set(CXX_LINKER "FORTRAN")
  set(FC_AUTO_R8 "-fdefault-real-8")
  set(CFLAGS "-mcmodel=medium")
  set(FREEFLAGS "-ffree-form")
  set(SFC "gfortran")
  set(SCXX "g++")
endif()
if("${COMPILER}" STREQUAL "intel")
  set(NETCDF_PATH "/sw/cs400_centos7.3_acfsoftware/netcdf/4.4.1.1/centos7.3_intel17.2.174/")
endif()
if("${MODEL}" STREQUAL "glc")
  set(CPPDEFS "${CPPDEFS}  -DUSE_PIO2 -DCPL_BYPASS")
endif()
if("${MODEL}" STREQUAL "ice")
  set(CPPDEFS "${CPPDEFS}  -DUSE_PIO2 -DCPL_BYPASS")
endif()
if("${MODEL}" STREQUAL "ocn")
  set(CPPDEFS "${CPPDEFS}  -DUSE_PIO2 -DCPL_BYPASS")
endif()
if("${COMPILER}" STREQUAL "intel")
  set(SLIBS "${SLIBS} -L/sw/cs400_centos7.3_acfsoftware/lapack/3.7.0/centos7.3_gnu6.3.0/lib -llapack -lblas -L/sw/cs400_centos7.3_acfsoftware/netcdf/4.4.1.1/centos7.3_intel17.2.174/lib -lnetcdff -lnetcdf -lgfortran")
  set(CPPDEFS "${CPPDEFS}  -DFORTRANUNDERSCORE -DNO_R16 -DCPRINTEL -DCPL_BYPASS")
  if("${compile_threaded}" STREQUAL "TRUE")
    set(CXXFLAGS "${CXXFLAGS}  -qopenmp")
    set(FFLAGS "${FFLAGS}  -qopenmp")
    set(CFLAGS "${CFLAGS}  -qopenmp")
  endif()
  if("${DEBUG}" STREQUAL "TRUE")
    set(CXXFLAGS "${CXXFLAGS}  -O0 -g")
    set(FFLAGS "${FFLAGS}  -O0 -g -check uninit -check bounds -check pointers -fpe0 -check noarg_temp_created")
    set(CFLAGS "${CFLAGS}  -O0 -g")
  endif()
  if("${DEBUG}" STREQUAL "FALSE")
    set(CXXFLAGS "${CXXFLAGS}  -O2")
    set(FFLAGS "${FFLAGS}  -O2 -debug minimal")
    set(CFLAGS "${CFLAGS}  -O2 -debug minimal")
  endif()
  if("${compile_threaded}" STREQUAL "TRUE")
    set(LDFLAGS "${LDFLAGS}  -qopenmp")
  endif()
endif()
if("${COMPILER}" STREQUAL "gnu")
  set(CPPDEFS "${CPPDEFS}  -DFORTRANUNDERSCORE -DNO_R16 -DCPRGNU -DCPL_BYPASS")
  if("${compile_threaded}" STREQUAL "TRUE")
    set(CFLAGS "${CFLAGS}  -fopenmp")
  endif()
  if("${MODEL}" STREQUAL "csm_share")
    set(CFLAGS "${CFLAGS}  -std=c99")
  endif()
  if("${compile_threaded}" STREQUAL "TRUE")
    set(FFLAGS "${FFLAGS}  -fopenmp")
  endif()
  if("${DEBUG}" STREQUAL "TRUE")
    set(FFLAGS "${FFLAGS}  -g -Wall -Og -fbacktrace -fcheck=bounds -ffpe-trap=invalid,zero,overflow")
    set(CFLAGS "${CFLAGS}  -g -Wall -Og -fbacktrace -fcheck=bounds -ffpe-trap=invalid,zero,overflow")
  endif()
  if("${DEBUG}" STREQUAL "FALSE")
    set(FFLAGS "${FFLAGS}  -O")
    set(CFLAGS "${CFLAGS}  -O")
  endif()
  if("${MODEL}" STREQUAL "cism")
    set(CMAKE_OPTS "${CMAKE_OPTS}  -D CISM_GNU=ON")
  endif()
  if("${compile_threaded}" STREQUAL "TRUE")
    set(LDFLAGS "${LDFLAGS}  -fopenmp")
  endif()
endif()
